image: dldl/sphinx-server

job:
  script:
    - uname -a

pages:
  script:



pages:
  script:
  - make -C docs html
  - mv docs/build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

