apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cinder
# the defualt strategy for deployments is
#StrategyType:           RollingUpdate
#MinReadySeconds:        0
#RollingUpdateStrategy:  1 max unavailable, 1 max surge
spec:
  selector:
    matchLabels:
      app: test-cinder
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: test-cinder
    spec:
      containers:
      - name: test-cinder
        image: oz123/cinder-test
        env:
          - name: DATABASE_DIR
            value: "/app/vol"
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        imagePullPolicy: Always
        volumeMounts:
        - name: database
          mountPath: "/app/vol"
      nodeSelector:
        failure-domain.beta.kubernetes.io/region: de-nbg6-1

      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: test-cinder-volume
