apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-cinder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-cinder
    spec:
      containers:
      - name: test-cinder
        image: oz123/cinder-test
        env:
          - name: DATABASE_DIR
            value: "/app/vol"
        imagePullPolicy: Always
        volumeMounts:
        - name: database
          mountPath: "/app/vol"
      nodeSelector:
        failure-domain.beta.kubernetes.io/region: de-nbg6-1

      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: test-cinder-volume
