apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: test-cinder-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: default-de-nbg6-1a

