apiVersion: v1
kind: Service
metadata:
  name: test-cinder
  labels:
    app: test-cinder
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: test-cinder
